### ISSUE TITLE
Android 出现闪退

### ISSUE THREAD

**Issue by lfyhhb116** [yyyyu/react-native-geetest-sensebot#3]
您好  在使用的过程中会出现崩溃 麻烦您看看 

错误日志:
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.geetest.sdk.Bind.GT3GeetestBindListener.gt3GeetestStatisticsJson(org.json.JSONObject)' on a null object reference
at com.geetest.sdk.Bind.GT3GeetestUtilsBind$O000000o.O000000o(GT3GeetestUtilsBind.java:559)
at com.geetest.sdk.Bind.GT3GeetestUtilsBind$O000000o.onPostExecute(GT3GeetestUtilsBind.java:517)
at android.os.AsyncTask.finish(AsyncTask.java:727)
at android.os.AsyncTask.access$600(AsyncTask.java:180)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
at android.os.Handler.dispatchMessage(Handler.java:109)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:7470)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

其它信息
"react-native": "0.55.4",
"@yyyyu/react-native-geetest-sensebot": "^1.0.4",

我看了GT3GeetestUtilsBind.java的源码 ，有些疑惑

![31555426496_ pic_hd](https://user-images.githubusercontent.com/10398295/56220732-80e1f480-609b-11e9-83dd-86f74e713639.jpg)

请问为什么不做判断，不知道是不是因为这个原因导致奔溃的，麻烦您看看，谢谢

**Comment by yyyyu** [comment]
出错的代码是极验SDK(版本3.5.3)内部代码, 我看了下最新版更新到4, 可能修复了问题, 其中调用方式也出现了变化, 近期会找个时间更新一下新版本, 可能会修复这个问题, 详细原因请资讯极验平台

**Comment by lfyhhb116** [comment]
嗯嗯 谢谢   期待您的更新

**Comment by yyyyu** [comment]
已经升级为版本2.0, 调用方式都做出了改动, 欢迎使用, 出现问题可以提 issue
